### ISSUE TITLE
Das Hauptbild soll zu einem Slider werden

### ISSUE THREAD

**Issue by izmailov03** [izmailov03/uh#1]
Es wurde schon versucht den Bootstrap Slider in den Willkommensbereich einzubauen. Allerdings gab es Probleme bei der Überlappung des Textes und der Responsive-Darstellung

**Comment by Reda1000** [comment]
Willkommensbereich home-section und intro? 
Slider: Wo ist dieser zu finden? Oder meinst du einen neuen Slider?

**Comment by izmailov03** [comment]
Ich lade soeben die bilder auf git hoch. pull  es dir mal.

Der home bereich soll ein slider sein, aber mit jeder slide soll mit dem hometext und dem scroll icon überdeckt sein

**Comment by Reda1000** [comment]
carousel = slider?

**Comment by Reda1000** [comment]
carousel eingebaut... passt in etwa?... noch nicht komplett

**Comment by izmailov03** [comment]
verkleiner mal bitte dein Fenster, dann kommt genau der Fehler, der auch bei mir war. Kann man das beheben?

**Comment by Reda1000** [comment]
mit background-size = cover und background-position = top center behoben. Bild deßhalb aus img als background-image verwendet.
