### ISSUE TITLE
Mailscript für das Formular programmieren

### ISSUE THREAD

**Issue by izmailov03** [izmailov03/uh#3]

**Comment by Reda1000** [comment]
Sollte laufen... in conact.php noch deutsche texte eintragen bzw email-empfänger und titel der mail

**Comment by izmailov03** [comment]
Script funktioniert einwandfrei. Wurde online getestet. Allerdings löscht sich der inhalt nach dem Absenden nicht.

**Comment by Reda1000** [comment]
Eingefügt...

**Comment by izmailov03** [comment]
David kannst du bitte das Mailscript noch so anpassen, dass das Namensfeld und die Telefonnummer im mailtext mit übergeben werden

**Comment by Reda1000** [comment]
Ok, alles in Nachrichtenkörper integriert:
Name: Testname
Tel.: 043242423432

Nachricht:
Hier kommt die Nachricht
