### ISSUE TITLE
Slider Effekt verbessern

### ISSUE THREAD

**Issue by izmailov03** [izmailov03/uh#4]
sobald sich ein slider verschiebt, entsteht links eine leere Fläche.

**Comment by Reda1000** [comment]
Quick fix:
``    carousel-inner > item: {
    ...
    transition: left 0.6s ease-in-out 0s; /*use something smaller than 0.6s for moving duration*/
    }``

**Comment by izmailov03** [comment]
ich habe langsames schieben gemacht, damit es angenehmer aussieht. :laughing: 

Deswegen ist der weiße rand erst zu sehen :laughing:

**Comment by Reda1000** [comment]
Gut zu wissen ;) Dann muss ich mal in die JS schauen, die die CSS Klasse left und right setzt
